CREATE TABLE IF NOT EXISTS app_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(30)  NOT NULL
);

COMMENT ON TABLE app_users IS 'Usuários HTTP Basic da API (senha com hash)';
COMMENT ON COLUMN app_users.role IS 'USER | ADMIN';

CREATE TABLE IF NOT EXISTS members (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome            VARCHAR(200) NOT NULL,
    atribuicao      VARCHAR(30)  NOT NULL,
    criado_em       TIMESTAMPTZ  NOT NULL
);

COMMENT ON TABLE members IS 'Membros criados pela API externa (nome + atribuição)';
COMMENT ON COLUMN members.atribuicao IS 'FUNCIONARIO | GERENTE | OUTRO';

CREATE TABLE IF NOT EXISTS projects (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                VARCHAR(255)  NOT NULL,
    data_inicio         DATE            NOT NULL,
    previsao_termino    DATE            NOT NULL,
    data_real_termino   DATE,
    orcamento_total     NUMERIC(19, 2)  NOT NULL,
    descricao           VARCHAR(4000) NOT NULL,
    gerente_id          BIGINT          NOT NULL,
    status              VARCHAR(40)     NOT NULL,
    CONSTRAINT fk_projects_gerente
        FOREIGN KEY (gerente_id) REFERENCES members (id)
);

COMMENT ON TABLE projects IS 'Projetos do portfólio';
COMMENT ON COLUMN projects.status IS 'EM_ANALISE | ANALISE_REALIZADA | ... | ENCERRADO | CANCELADO';

CREATE INDEX IF NOT EXISTS idx_projects_status ON projects (status);
CREATE INDEX IF NOT EXISTS idx_projects_gerente ON projects (gerente_id);

CREATE TABLE IF NOT EXISTS project_members (
    project_id  BIGINT NOT NULL,
    member_id   BIGINT NOT NULL,
    PRIMARY KEY (project_id, member_id),
    CONSTRAINT fk_pm_project
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CONSTRAINT fk_pm_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

COMMENT ON TABLE project_members IS 'Alocação de funcionários aos projetos (N:N)';

CREATE INDEX IF NOT EXISTS idx_project_members_member ON project_members (member_id);
